# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    maintance_mode_listener:
        class: AppBundle\EventListener\Request\MaintanceModeListener
        arguments: ['@kernel']
        tags:
          -  { 'name': 'kernel.event_listener', 'event': 'kernel.request', 'method': 'onKernelRequest', 'priority': 8192 }

